services:

  cassandra:
    build: ./cassandra
    container_name: sMall_cassandra
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    env_file:
      - .env
    volumes:
      - ./cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml # override
  #      - cassandra-data:/var/lib/cassandra

  mysql:
    image: mysql:8.0
    container_name: sMall_mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_DATABASE: ${MYSQL_DB}
    restart: unless-stopped
  #    volumes:
  #      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: sMall_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "${REDIS_PWD}" ]
  #    volumes:
  #      - redis-data:/data

#volumes:
#  redis-data:
#  cassandra-data:
#  mysql_data: