services:

  redis:
    image: redis:latest
    container_name: sMall_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PWD}"]
#    volumes:
#      - redis-data:/data

  cassandra:
    build: ./cassandra
    container_name: sMall_cassandra
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    env_file:
      - .env
    volumes:
      - ./cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml # override
#      - cassandra-data:/var/lib/cassandra

#volumes:
#  redis-data:
#  cassandra-data: