version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: sMal_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    env_file:
      - common/common.env
    command: ["redis-server", "--requirepass", "${REDIS_PWD}"]
#    volumes:
#      - redis-data:/redis-data

## Without top-level volume declaration, an anonymous volume with a random name is created
#volumes:
#  redis-data: